To review
testobject-sample-test-frameworks/Java-JUnit-Appium-Android-Suite pull request #2
Opened 2017-02-22 18:26 UTC by ragog

2017-02-22 19:19 UTC, KevinMarkVI commented
Looks good to me. @ndmanvar ?

2017-02-27 17:04 UTC, ndmanvar commented
Just one small change regarding SUITE. Other than that, good to me! 👍

2017-02-27 17:05 UTC, ndmanvar requested changes

2017-02-27 17:05 UTC, ndmanvar commented on src/test/java/com/yourcompany/SampleSauceTest.java
> +@TestObject(testObjectApiKey = "INSERT_API_KEY_HERE", testObjectSuiteId = 12345)
@ragog I don't think we should hard-code the testId?
Let's remove that and use `INSERT_SUITE_NUMBER_HERE` or an environment variable?

Happy to discuss.

2017-02-28 11:20 UTC, ragog commented on src/test/java/com/yourcompany/SampleSauceTest.java
> +@TestObject(testObjectApiKey = "INSERT_API_KEY_HERE", testObjectSuiteId = 12345)
@ndmanvar the testObjectSuiteId is automatically overridden in this case (we are listening for the environment variable within our library). Putting a random value there at least allows us to override it without running into an error when we try to compile. You can only insert constant values in annotations, too, so we are kind of limited in how we approach this.

2017-03-06 02:46 UTC, merged